[terminal]
# The VT that greetd should use. systemd usually reserves tty1 for the display manager.
vt = 1

[default_session]
# Tell greetd to use tuigreet, and tell tuigreet to launch labwc
command = "tuigreet --time --cmd labwc"

# The user to run the greeter as. 
# The greetd package automatically creates this 'greetd' user.
user = "greetd"
